---
abstract: 'Generate PNG graphical representations of Data Matrix barcodes'
author:
  - 'Kasem Omary <kasemo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Barcode-DataMatrix-PNG
requires:
  Any::Moose: 0
  Barcode::DataMatrix: 0
  Carp: 0
  GD: 0
  Moose: 0
version: 0.05
